// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmjuusdeqqsgcubgiwdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtanV1c2RlcXFzZ2N1Ymdpd2R2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTIxMjcsImV4cCI6MjA3MTk2ODEyN30.ge1yCVl68q3DkNBaVQD2Q7olUBGYrxgs0Vs1hwpPM9o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});